project:
  type: website
  output-dir: docs

website:
  title: "Publishing Quarto websites with GitHub pages"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - href: intro.qmd
        text: "Quarto Websites" 
      - href: github.qmd
        text: "Publish on GitHub"
      - href: customize.qmd
        text: "Do it in Style"
      - about.qmd
    right:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/ucldw26-quarto-websites

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



